global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: 'renanreismartins@gmail.com'
  smtp_auth_password: 'xivdmywwoqdktqpq'
  smtp_require_tls: true
  smtp_from: 'renanreismartins@gmail.com'
route:
  receiver: example-email
  group_by: [alertname]
receivers:
  - name: example-email
    email_configs:
      - to: 'renanreismartins@gmail.com'
