global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alert-manager:9093
scrape_configs:
  - job_name: example
    static_configs:
    - targets:
      - host.docker.internal:8000
